### ISSUE TITLE
lua md5 implementation origin and license ?

### ISSUE THREAD

**Issue by tst2005** [Overtorment/NoobHub#15]
Hello,

I see you have a good lua md5 implementation :
* [client/lua-gideros/main.lua](https://github.com/Overtorment/NoobHub/blob/master/client/lua-gideros/main.lua#L89-L231) line 89-231
* [client/lua-love/main.lua](https://github.com/Overtorment/NoobHub/blob/master/client/lua-love/main.lua#L94-L236) line 94-236
* [client/lua-gideros/main.lua](https://github.com/Overtorment/NoobHub/blob/master/client/lua-gideros/main.lua#L89-L231) line 89-231

Who are the autor of this `md5` function ?
Where did it comes ?
Under which license did it released ?

Best Regards,

**Comment by Overtorment** [comment]
Hello, this is stripped version of https://github.com/clementfarabet/lua---bitop/blob/master/md5test.lua and it says its "Public Domain".

**Comment by tst2005** [comment]
Thanks a lot !

**Comment by tst2005** [comment]
Thanks a lot !
