### ISSUE TITLE
Can't get external connections to work

### ISSUE THREAD

**Issue by Substance12** [Overtorment/NoobHub#18]
There's no way I can connect to the server from an external IP. It works if I use 127.0.0.1 or use my PC's private IP, but it doesn't work if I try with the public IP.

I've already tried adding "0.0.0.0", "localhost" and "127.0.0.1" to server.listen(cfg.port), forwarding the 1337 port, editing iptables. Nothing works.

**Comment by Overtorment** [comment]
Which hoster are you using? Sounds like AWS default security groups policy. I regularly hear from folks on AWS who have troubles running Noobhub there.
Try this one 46.4.76.236  this is pretty much default setup on Hetzner (german hoster).

**Comment by Substance12** [comment]
I'm just using my own PC to test since in my game, one of the players will host the server.

And nope, using that address didn't work either, it gave me "Exception: Error: listen EADDRNOTAVAIL 46.4.76.236:1337"

**Comment by Substance12** [comment]
Closing this. I tried opening the port again and this time it worked. Not sure why, I had opened the 1337 port earlier and nothing had changed. Oh well, thanks for the help anyway. Awesome work!
