### ISSUE TITLE
JS code

### ISSUE THREAD

**Issue by SneakBug8** [Overtorment/NoobHub#24]
I have error in
var net = require("net")
Screens of errors: http://m.imgur.com/h0Lug2v

I just runned client-test.js, so it isn't my work, i think...

**Comment by Overtorment** [comment]
Looks like youre trying to run it in browser. Actually its not ported for browsers yet.
@dr3am3r

**Comment by SneakBug8** [comment]
Ooh...
Will you port NoobHub to browser JavaScript? It would be very useful, because i have mobile client in Corona and web (PC) client in JavaScript, and i would like to use same server in both clients...

**Comment by Overtorment** [comment]
Should be relatively easy, you can do it yourself.
I dont plan doing it myself nearest future.

**Comment by SneakBug8** [comment]
Oh. I am pretty noob in JS, so i think, that i can't :(

**Comment by dr3am3r** [comment]
it requires a websocket proxy to work with a browser, currently, it's not developed. I'll probably take it, @SneakBug8, I'll let you informed
