### ISSUE TITLE
What about TLS/SSL

### ISSUE THREAD

**Issue by florindumitru** [Overtorment/NoobHub#25]
How can I implement tls/ssl into noobhub ?

Thanks and great job

**Comment by Overtorment** [comment]
tls/ssl was never intended. I wonder if there's a smart way to add encryption.
First  thought is to add asymmetric crypto lib to clients who send messages.

**Comment by florindumitru** [comment]
Maybe can be use this https://github.com/coronalabs/plugins-sample-openssl/blob/master/luasec/main.lua ...if yes please help me to to that !!!!

**Comment by Overtorment** [comment]
Im not planning to implement encryption atm, but might accep pull request
