### ISSUE TITLE
Problem running NoobHub on AWS

### ISSUE THREAD

**Issue by britzl** [Overtorment/NoobHub#28]
I'm trying to run the server on AWS. I can connect (I see the "New Client" log) but socket.on() never fires. I have verified that the client sends the subscribe message (In my case 40 bytes written and no error), but it never reaches the server. Do you happen to know of anything in particular that needs to be done to get it to work on AWS?

**Comment by Overtorment** [comment]
I know for sure that some folks run Noobhub server on AWS, so it should work.
My guess - check your firewall/port forwarding or something. I think Amazon has all ports forbidden by default

**Comment by britzl** [comment]
Thanks! Do you happen to have contact details for anyone using NoobHub on AWS?

**Comment by Overtorment** [comment]
No, that was a long time ago, dont even remember who reached out to me to help them :-)
Another guess is proably major nodejs version incompatibility. Dont know, maybe they released some breaking changes while I wasnt looking :-P

**Comment by britzl** [comment]
We got it working. It was either a AWS group or load balancer issue (not sure which) :-)
