### ISSUE TITLE
Buffer() deprecated in Node 10

### ISSUE THREAD

**Issue by tylerR94** [Overtorment/NoobHub#29]
Buffer() has been deprecated in Node v10. buffer.alloc() seems very suitable to replace buffer() in noobhub. I made the change myself and it seems to be running with stability on my end, just thought I'd raise the issue here so that people going forward are aware of this deprecation error and how to address it.

**Comment by Overtorment** [comment]
Thanks! Why not submit PR? I’d be happy to merge

**Comment by tylerR94** [comment]
I'm quite a noob when it comes to git, so I'm not sure how to create one to be honest haha.

**Comment by tylerR94** [comment]
Oh wait, it looks like someone did that back in January of last year? It's the only pull request I see listed.

**Comment by Overtorment** [comment]
No its a failed attempt to rewrite or something...
Well, looks like a perfect case to learn git for you!

**Comment by tylerR94** [comment]
Alright, give me a bit to figure it out and then I'll push a PR :)

**Comment by Overtorment** [comment]
1. fork the repo (in github interface)
2. clone forked repo to your machine
3. create branch, work on it, commit, push
4. back to github UI, create pull request (github will detect new branch and will ask you whether you want to create a PR)

**Comment by tylerR94** [comment]
Done and done, easier than I expected!

**Comment by Overtorment** [comment]
good job!
